### ISSUE TITLE
generic option to disable/enable use-catalog button

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#115]

**Comment by dsavchenko** [comment]
Also decided to disable catalog editing functionality

**Comment by volodymyrss** [comment]
here is what to remove, right?

![image](https://user-images.githubusercontent.com/3909535/148951102-91f4a6d4-7374-4893-9c58-ddd31dac5f88.png)

also editing in the cells.

**Comment by motame** [comment]
Implemented !
A new option is added to the instrument settings at installation time: enable_use_catalog.
It's a boolean. If true or absent the functionally use_catalog will be enabled otherwise not.
Here is an example with GW: 
```
function astrooda_gw_install()
{
...
  $module_settings = array(
...
    'enable_use_catalog' => FALSE
  );
...
}
```

![firefox_R7aHvI4wQO](https://user-images.githubusercontent.com/44972498/150352620-721a07bf-1f6a-4120-a654-7cec38d72bc1.png)

Can be closed !

**Comment by volodymyrss** [comment]
@dsavchenko  looks good for you?

**Comment by dsavchenko** [comment]
> @dsavchenko looks good for you?

Yes!
