### ISSUE TITLE
Update Bokeh JS libraries in frontend

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-astrooda#127]
Currently, the Bokeh libraries for the version 0.12.16 are served by frontend server. 
We need to update to the recent 2.4.2. 

I can simply replace the _bokeh.min.js_ and _bokeh-widgets.min.js_ with the current ones, but it would be better to rely on CDN.
How to do it properly? Just add appropriate <script> tags to the template, or there is a better way? 

Now, we need these:
```
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.2.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.2.min.js" crossorigin="anonymous"></script>
```
The additional ones are currently not necessary
```
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.4.2.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.4.2.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-2.4.2.min.js" crossorigin="anonymous"></script>
```

**Comment by dsavchenko** [comment]
After reading some docs, I found the way #128

**Comment by volodymyrss** [comment]
are we happy with how it is in staging ? LegacySurvey works! And slider is indeed good. Previous one was annoying.

**Comment by dsavchenko** [comment]
Seems like we may close this issue

**Comment by motame** [comment]
It's closed but just FYI, nice to know :-) :
[Why you shouldn't use external javascript files](https://www.elxis.org/fr/blog/external-js-files.html)

**Comment by dsavchenko** [comment]
> It's closed but just FYI, nice to know :-) : [Why you shouldn't use external javascript files](https://www.elxis.org/fr/blog/external-js-files.html)

In this case, I wouldn't agree. 

All this is true for the random external website, but here we use CDN, and it is what CDN is intended to be used. 
CDNs actually increase script's availability.

This is a recommended way of embedding bokeh https://docs.bokeh.org/en/latest/docs/user_guide/embed.html#userguide-embed-standalone

I think, we had a discussion about this some time ago

**Comment by volodymyrss** [comment]
> It's closed but just FYI, nice to know :-) : [Why you shouldn't use external javascript files](https://www.elxis.org/fr/blog/external-js-files.html)

Thanks @motame . Indeed, it's not useful to rely on various external links often given in examples.
But this article does not discuss CDN, which is a special case of external files. 

The whole purpose of CDNs is to provide some of the "reusable" site content from somewhere else than a site.
With CDN, potentially large JS files are likely to be loaded from some mirror next to the user, often dramatically improving performance.
Also, this protects from DDOS attacks.
Of course, there is a question about what happens if the CDN breaks or is compromised. Or that they inevitably collect access information.
But given that a CDN has only one job - make sure these static files are provided securely and safely, the are made to do this job rather well. At least most of the internet thinks so and uses them.

Bokeh specifically advises to use either CDN or local files:  https://docs.bokeh.org/en/latest/docs/user_guide/embed.html
@dsavchenko chose here to follow first of the options.

**Comment by volodymyrss** [comment]
Just as I was pushing "Comment" I saw @dsavchenko message!
Anyway, let us discuss next Monday with @motame
