### ISSUE TITLE
Expiration time of the web authentication token

### ISSUE THREAD

**Issue by motame** [oda-hub/frontend-astrooda#71]
Following the issue #70 what should be the value of the expiration time of the web authentication token ?
(maximum : 9999 minutes, ~6.94 days)
Please give your opinion/arguments ...

**Comment by volodymyrss** [comment]
* lower limits:
  * As of now, the token accompanies the job as it propagate through the system, so the the duration should be at least long enough to for the job to complete.
Typical job would not be longer than a day at most. That's why what we have now - 1 day - works just fine.
Maybe we can use 3 days, for safety.
  * as the user is interacting with the client/notebook or frontend, token should not suddenly expire. Typical session is probably hours at most. But it might happen that user leaves the interface and comes back later, starting new interaction with session which is about to expire. We put warnings in email, we could have some in the frontend. But it's not a big deal since once it expires new one can be generated.
  * peculiar for frontend interaction, token should better live longer than frontend session. Else "token expired" happens while user is logged in. Is there currently a limit on frontend session lifetime?
  
* upper limits
   * token accidentially left in the wild (in notebooks, in old emails, screenshots, etc) should not be exploitable. If the duration is 3 days, only little bad things can be done with it

If we find unusual cases
We could make a way to automatically extend token during execution, from secure reserved subsystems, if we have longer jobs.
We could also always generate new token (with just new expiration) when submitting the job.

**Comment by burnout87** [comment]
I agree with a duration not below 1 day and not above three.

> 
> If we find problematic situations, we can make further adjustments.
> We could make a way to automatically extend token during execution, from secure reserved subsystems, if we have longer jobs.
> We could also always generate new token (with just new expiration) when submitting the job.

This is indeed what I was suggesting in [https://github.com/oda-hub/dispatcher-app/issues/212](https://github.com/oda-hub/dispatcher-app/issues/212), re-generate token in case the request is taking long time to complete and the token is expired, or perhaps about to.

**Comment by volodymyrss** [comment]
Do you have any additional arguments or mine sound sufficient?

> > If we find problematic situations, we can make further adjustments.
> > We could make a way to automatically extend token during execution, from secure reserved subsystems, if we have longer jobs.
> > We could also always generate new token (with just new expiration) when submitting the job.
> 
> This is indeed what I was suggesting in [oda-hub/dispatcher-app#212](https://github.com/oda-hub/dispatcher-app/issues/212), re-generate token in case the request is taking long time to complete and the token is expired, or perhaps about to.

What I wrote here matches, not coincidentally, the title of that issue I made [oda-hub/dispatcher-app#212](https://github.com/oda-hub/dispatcher-app/issues/212). But your comment in that issue seems to be something different. We can discuss it there, it's not too relevant now.

**Comment by burnout87** [comment]
> Do you have any additional arguments or mine sound sufficient?

I think all the most relevant factors that might have an impact on the token expiration time have been taken into account. 

> Is there currently a limit on frontend session lifetime?

I think we already discussed about this with @motame , and said that there isn't actually one with Drupal. But of course I might be wrong. Perhaps @motame could indeed could clarify this point.

**Comment by volodymyrss** [comment]
> > Do you have any additional arguments or mine sound sufficient?
> 
> I think all the most relevant factors that might have an impact on the token expiration time have been taken into account.

ok, good!

> 
> > Is there currently a limit on frontend session lifetime?
> 
> I think we already discussed about this with @motame , and said that there isn't actually one with Drupal. But of course I might be wrong. Perhaps @motame could indeed could clarify this point.

Yes. And if there is no limit, current approach of providing a suggestion to re-login is fine.

**Comment by volodymyrss** [comment]
Following last discussion, we can set server-side expiration of drupal session at 3 days (currently ~3 weeks?) and token duration 4 days.
