### ISSUE TITLE
pressing Enter when entering object name deactivates "Resolve" button

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-astrooda#84]
**Expected behaviour**: resolve source name

Also, validation of the common parameters fields is triggered with this.

To activate the button back one needs to edit the field again. Afterwards, the bug doesn't repeat.

**Comment by volodymyrss** [comment]
known since a while. Good to track here, thanks.

**Comment by motame** [comment]
Exactly ! whenever the user push Enter key in any of the input fields.
Enter key should be ignored in all the common parameter inputs, as it does not make sense to submit a request from there.
The user need first to select an instrument and fill instrument parameters before submitting any request.
For the name resolution, the user has to click on resolve and not push Enter key.

An this is not enough in fact !
If any bad value entered in RA, DEC, start/end time will block the resolve button.
This is because the button is the submit button of the whole form of common parameters.
I'll open another issue to fix that ...

**Comment by volodymyrss** [comment]
@dsavchenko may want to see!

**Comment by dsavchenko** [comment]
> @dsavchenko may want to see!

Great!
